[build]
  publish = ".output/public"
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "22"
  PNPM_VERSION = "9"

# Production context: main branch deploys
[context.production]
  command = "pnpm run build"
  [context.production.environment]
    NUXT_ENV_DEPLOY_CONTEXT = "production"
    NODE_ENV = "production"

# Staging context: staging branch deploys  
[context.staging]
  command = "pnpm run build"
  [context.staging.environment]
    NUXT_ENV_DEPLOY_CONTEXT = "staging"
    NODE_ENV = "production"

# Deploy Preview context: pull request previews
[context.deploy-preview]
  command = "pnpm run build"
  [context.deploy-preview.environment]
    NUXT_ENV_DEPLOY_CONTEXT = "deploy-preview"
    NODE_ENV = "production"

# Branch deploy context: other branches
[context.branch-deploy]
  command = "pnpm run build"
  [context.branch-deploy.environment]
    NUXT_ENV_DEPLOY_CONTEXT = "branch-deploy"
    NODE_ENV = "production"

# Dev context: local development
[context.dev.environment]
  NUXT_ENV_DEPLOY_CONTEXT = "development"
  NODE_ENV = "development"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Environment-specific redirects can be added here
# Example: redirect old URLs, handle legacy routes, etc.

# Functions settings (if using Netlify Functions)
[functions]
  directory = "server/functions"
  
# Build plugin settings
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    enable_only_on_production = true

# Form handling settings
[template.environment]
  FORM_NOTIFICATIONS_EMAIL = "notifications@example.com" 