name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy-to-netlify: # Renamed job for clarity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # fetch-depth: 0 is usually not needed for simple deploys,
        # but harmless if you have a specific reason for it.

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        # You can specify a pnpm version if needed:
        # with:
        #   version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Keep your desired Node.js version
          # registry-url is usually not needed unless publishing packages
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile # Use --frozen-lockfile for CI
        env:
          # These are needed if your 'pnpm install' (e.g., postinstall scripts)
          # or 'nuxi prepare' (which runs implicitly with Nuxt) requires them.
          KIRBY_BASE_URL: ${{ secrets.KIRBY_BASE_URL }}
          KIRBY_API_TOKEN: ${{ secrets.KIRBY_API_TOKEN }}

      - name: Build Nuxt application
        run: pnpm run build
        env:
          # NITRO_PRESET for Nuxt 3:
          # For Netlify, Nuxt will typically auto-detect or you can explicitly set it.
          # If Nuxt doesn't auto-detect correctly, you might use 'netlify' or 'netlify-static'.
          # Often, you don't need to set NITRO_PRESET manually for Netlify as Nuxt is good at detection.
          # NITRO_PRESET: netlify # or netlify-static, try without first
          KIRBY_BASE_URL: ${{ secrets.KIRBY_BASE_URL }}
          KIRBY_API_TOKEN: ${{ secrets.KIRBY_API_TOKEN }}
          # Add any other build-time environment variables your Nuxt app needs

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './.output/public' # Standard Nuxt 3 output directory
          production-branch: main
          # Optional: Specify a deploy message
          # deploy-message: "Deploy from GitHub Actions: ${{ github.sha }}"
          # Optional: Control comments on PRs/commits
          # enable-pull-request-comment: false
          # enable-commit-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 5 # Optional: Adjust deploy timeout
